### ISSUE TITLE
VirusTotal detects malware?

### ISSUE THREAD

**Issue by aspenmayer** [morishin/XDeck#16]
[https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/](https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/)

The sandbox C2AE flags this file as: STEALER
The sandbox ReaQta-Hive flags this file as: MALWARE

**Comment by morishin** [comment]
> Potentially a false positive. For what it's worth, the URL for latest release seems clean:
> 
> https://www.virustotal.com/gui/url/8d4033bb0e0d4543c4d009f13e634afc15ec33b1b5f8216ba1b4d3c38f28a5ff/

The application zip file seems clean. So I think I can close this issue.
Thanks.

**Comment by elvey** [comment]
Something was fishy about this issue in the first place.   Currently, the link in the OP by @aspenmayer  (https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/) currently shows the fileandroid-cts-7.1_r6-linux_x86-arm.zip  - which sure as heck isn't XDeck - and shows 0 malware detections; rather it shows the file is distributed by Microsoft, etc. ([Explanation](https://blog.virustotal.com/2021/08/introducing-known-distributors.html)

(The OP also shows "edited by [aspenmayer](https://github.com/aspenmayer)" but I checked the edit history, and the edit didn't change the URL even one bit*, just the formatting. )

*literally
