### ISSUE TITLE
how to run xdeck in lower version Mac os

### ISSUE THREAD

**Issue by eleven520** [morishin/XDeck#19]
like version 11.7.10 Big Sur

thanks for your workout

**Comment by morishin** [comment]
1. Switch "Minimum Deployments" macOS version to 11.x
    ![スクリーンショット 2024-08-15 14 11 51](https://github.com/user-attachments/assets/2ec4fb95-f1bd-4c7f-b46e-8bd750314d4c)

2. Fix these build errors (rewrite them into syntax compatible with lower versions)
    ![スクリーンショット 2024-08-15 14 11 31](https://github.com/user-attachments/assets/bf9a2c6e-72b0-413a-8c30-578eccd7c219)

**Comment by eleven520** [comment]
thanks for your answer !
